formated

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -44,61 +44,61 @@ grep -q "termux-fingerprint" $FILE;
 
 #if true then remove lock
 if [ $? -eq 0 ]; then
-	echo -e $Y" [*] Removing Lock......................\r"
-	echo
-	sleep 1
-	echo -e $G" [!] Authentication Required\r $U"
-	sleep 1
+    echo -e $Y" [*] Removing Lock......................\r"
+    echo
+    sleep 1
+    echo -e $G" [!] Authentication Required\r $U"
+    sleep 1
 
-	#Authenticate fingerprint
-	termux-fingerprint | grep -q "AUTH_RESULT_SUCCESS"
+    #Authenticate fingerprint
+    termux-fingerprint | grep -q "AUTH_RESULT_SUCCESS"
 
-	#if success delete lock
-	if [ $? -eq 0 ]; then
-		sed -i '/termux-fingerprint/d' $FILE
-		rm -f $0
-		sleep 2
-		echo -e $Y" [!] Removing Lock......................$G DONE"
-		echo
+    #if success delete lock
+    if [ $? -eq 0 ]; then
+        sed -i '/termux-fingerprint/d' $FILE
+        rm -f $0
+        sleep 2
+        echo -e $Y" [!] Removing Lock......................$G DONE"
+        echo
 
-	#else exit
-	else
-		echo -e $Y" [!] Removing Lock......................$R ERR"
-		echo
-		echo -e $R" [!] Exiting...                               "
-		exit
-	fi 
+    #else exit
+    else
+        echo -e $Y" [!] Removing Lock......................$R ERR"
+        echo
+        echo -e $R" [!] Exiting...                               "
+        exit
+    fi 
 
 #if lock do not exist. set one
 else
-	echo -ne $Y" [*] Installing Dependencies............\r"
-	apt-get update &> /dev/null && apt-get upgrade -y &> /dev/null
-	apt-get install termux-api -y &> /dev/null
-	sleep 2
-	echo -e $Y" [!] Installing Dependencies............$G DONE"
-	echo
-	echo -e $Y" [*] Setting Lock......................."
-	echo
-	sleep 1
-	echo -e $G" [!] Authentication Required\r $U"
-	sleep 1
+    echo -ne $Y" [*] Installing Dependencies............\r"
+    apt-get update &> /dev/null && apt-get upgrade -y &> /dev/null
+    apt-get install termux-api -y &> /dev/null
+    sleep 2
+    echo -e $Y" [!] Installing Dependencies............$G DONE"
+    echo
+    echo -e $Y" [*] Setting Lock......................."
+    echo
+    sleep 1
+    echo -e $G" [!] Authentication Required\r $U"
+    sleep 1
 
-	#Test if fingerprint working.
-	termux-fingerprint | grep -q "AUTH_RESULT_SUCCESS"
+    #Test if fingerprint working.
+    termux-fingerprint | grep -q "AUTH_RESULT_SUCCESS"
 
-	#if true set lock
-	if [ $? -eq 0 ]; then
-		sed -i '2 a termux-fingerprint -c Exit | grep -q "AUTH_RESULT_SUCCESS"; [ $? -ne 0 ] && exit' $FILE
-		sleep 2
-		echo -e $Y" [!] Setting Lock.......................$G DONE"
-		echo
+    #if true set lock
+    if [ $? -eq 0 ]; then
+        sed -i '2 a termux-fingerprint -c Exit | grep -q "AUTH_RESULT_SUCCESS"; [ $? -ne 0 ] && exit' $FILE
+        sleep 2
+        echo -e $Y" [!] Setting Lock.......................$G DONE"
+        echo
 
-	#else skip setup. and exit.	
-	else
-		echo -e $Y" [!] Setting Lock.......................$R ERR"
-		echo
-		echo -e $R" [!] Exiting...                               "
-		exit
-	fi
+    #else skip setup. and exi
+    else
+        echo -e $Y" [!] Setting Lock.......................$R ERR"
+        echo
+        echo -e $R" [!] Exiting...                               "
+        exit
+    fi
 fi
 
